[build]
command = "npm run build"
publish = "build/client"

[[redirects]]
from = "/it"
to = "/it-maintenance"
status = 301

[[redirects]]
from = "/perfume"
to = "/commercial-aroma-solutions"
status = 301

[[redirects]]
from = "/profile"
to = "/downloads"
status = 301

[[redirects]]
from = "/products"
to = "/commercial-aroma-solutions"
status = 301

[[redirects]]
from = "/*"
to = "/404.html"
status = 404
